VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-22.04"  # Image Vagrant récupérable via Vagrant Cloud

  config.vm.define "pythonWebapp" do |pythonWebapp|
    pythonWebapp.vm.hostname = "pythonWebapp"  # Nom de la machine 
    pythonWebapp.vm.network "private_network", ip: "192.168.56.10"  # Configure un réseau privé en statique

    # Ressources allouées 
    pythonWebapp.vm.provider "virtualbox" do |vb|
      vb.memory = "10240"  # 10 GiB de RAM
      vb.cpus = 2
    end
  end
end